# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 赵伟驰
# title: Senior Network System Administrator
email: wzhao42@outlook.com
website: wzstephen.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: facespics
github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: jameswgrant
linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  硕士研究生毕业于亚利桑大州立大学.主修计算机科学，专修软件工程，数据结构设计，机器学习和数据可视化.致力于成为一个踏实能干以及以解决问题为导向并且拥有丰富实践经验的工程师.拥有善于分析的特质和卓越的领导力.

content:
  - title: IT技能
    layout: text
    content: | # this will include new lines to allow paragraphs
      - 擅长于面向对象程序和后端的设计，开发，测试, 排除故障和计算机网络. 
      - 擅长于数据库管理, 统计分析,数据挖掘以及数据可视化. 
      - 对机器学习以及数据分析有着一定的实践和运用. 
      - 对虚拟现实的开发和测试以及对三维模型的设计和运用有着一定的经验. 
      - 能快速高效地抓住新理念，具有秀的项目管理以及组织能力, 既能团队协作，也能自我导向独立完成工作.
      - 编程语言：<mark>Java</mark> <mark>Python</mark> <mark>JavaScript</mark> <mark>ASP</mark> <mark>MATLAB</mark>
      - 交流语言：<mark>中文</mark> <mark>英文</mark> 

  - title: 教育背景 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: middle
        title: 亚利桑那州立大学富尔顿工程学院 （GPA 3.40/4.00）
        caption: 2015.08 - 2019.05
        sub_title: 本科 - 计算机科学
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        # description: | # this will include new lines to allow paragraphs
        #   During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

        #   I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.
      
      - layout: middle
        title: 亚利桑那州立大学富尔顿工程学院 （GPA 3.97/4.00）
        caption: 2019.06 - 2020.12
        sub_title: 硕士 - 计算机科学
  - title: 经历 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 亚利桑那州立大学
        link: www.asu.edu
        # link_text: boringcompany.com
        sub_title: 云虚拟平台开发员(亚利桑那-坦佩)
        caption: 2020.01 - 2020.03
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - 以学术研究和教育为目的协助开发开放式的虚拟实验平台(THOTH Lab). 
            - 拓展了包括软件定义网络和交换机控制器的教学模块.
            - 利用 Boto3 设计 RESTful 接口以拓展该平台服务器模块对于 AWS 的远程控制功能.
            - 参与并协助部分前端和后端的开发. 

      - layout: left
        title: 亚利桑那州立大学
        link: www.asu.edu
        # link_text: boringcompany.com
        sub_title: 研究项目助理(亚利桑那-坦佩)
        caption: 2020.01 - 2020.03
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - 利用研究论文（IR-CP-ABE）中的技术协助开发基于属性加密的安全系统
            - 使用 JAVA 语言在 Android 平台上实现 IR-CP-ABE 系统. 

      - layout: left
        title: 亚利桑那州立大学
        link: www.asu.edu
        # link_text: boringcompany.com
        sub_title: 研究项目助理(亚利桑那-坦佩)
        caption: 2020.01 - 2020.03
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - 协助组织与管理本科阶段的计算机科学课程. 
            - 协助 CSE205 面向对象程序设计，CSE412 数据库管理，CSE434 计算机网络，CSE464 软件 QA 和测试课程的答疑与教学.
      
  - title: 项目 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Map-Reduce 中地理空间数据分析
        link: https://github.com/WZStephen/Spatial-Data-Analysis
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          - 根据纽约出租车出行记录来进行空间分析。此项目的目的是通过Apache Spark的分布式记忆计算框架来识别在统计显著的模式中异常的模式. 
      
      - layout: middle
        title: 时序性的血糖监测数据分析.
        link: https://github.com/WZStephen/CGN-Data-Mining
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          - 收集血糖数据来对时间序列数据进行分析，进而选取有意义的统计数据和分析数据的其他特征.
    
      - layout: top-middle
        title: Large Mini-Batch 深度学习模型的计算引擎的基准测试
        link: https://github.com/WZStephen/Spark-Bench
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          - 研究计算引擎中的传统优化器 SGD，以及优化相关大数据集和 DNN 模式的性能。 
          - 将新式的 LARS-SGD 优化器集成到传统计算引擎中，对同一数据集合 DNN 模式进行基准测试.在 16384 批次中，测试样本的检测准确率达到 97.79%. 
    
      - layout: top-middle
        title: VAST Challenge 2015 设计数据可视化来解决问题 
        link: https://github.com/WZStephen/VAST-Challenge-2015-MC1
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          - 收集恐龙公园中某个事件中游客移动的时间序列数据并分析出有用的特征. 
          - 设计数据分析可视化来展示引起混乱的原因以及其中有价值的发现. 

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")
      - title: IT 技能

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
