title: Weichi Zhao
description: AI Infra notes, LLM serving updates, and personal resume.
url: "https://wzstephen.github.io"
baseurl: ""
timezone: Asia/Shanghai
permalink: /blog/:year/:month/:day/:title/
markdown: kramdown

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Weichi Zhao
